name: "Container Scan"
description: "Scan image for vulnerabilities"
author: "Atomist, Inc."
inputs:
  image:
    required: true
    description: "Name of image including repository and tag"
runs:
  using: "node12"
  main: "dist/index.js"
