name: "Container Scan"
description: "Scan image for vulnerabilities"
author: "Atomist, Inc."
inputs:
  image:
    required: true
    description: "Docker image name"
  tags:
    required: false
    description: "Docker image tags"
  url:
    required: true
    description: "Webhook url"
runs:
  using: "node12"
  main: "dist/index.js"
