name: "Container Scan"
description: "Scan image for vulnerabilities"
author: "Atomist, Inc."
inputs:
  tags:
    required: false
    description: "Docker image tags"
  url:
    required: true
    description: "Webhook url"
  dockerfile:
    required: false
    description: "Path to the Dockerfile used during build"
    default: Dockerfile
  token:
    description: "Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`."
    required: false
    default: ${{ github.token }}
runs:
  using: "node12"
  main: "dist/index.js"
